apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "etcd-hb-fullname" . }}-etcd-certs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "etcd-hb-fullname" . }}-etcd-certs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "etcd-hb-fullname" . }}-etcd-certs
subjects:
- kind: ServiceAccount
  name: {{ template "etcd-hb-fullname" . }}-etcd-certs
  namespace: {{.Release.Namespace}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "etcd-hb-fullname" . }}-etcd-certs
rules:
{{ if .Values.podSecurityPolicy.enabled}}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs:     ["use"]
    resourceNames:
      - {{ .Values.podSecurityPolicy.name }}
{{ end }}
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs:     ["use"]
    resourceNames: ["helm-broker.privileged"]