apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "helm-broker.privileged"
spec:
  allowedCapabilities: ["*"]
  privileged: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  volumes:
    - '*'